/* generated using openapi-typescript-codegen -- do not edit */
/* istanbul ignore file */
/* tslint:disable */
/* eslint-disable */
export enum FiatAsset {
  AED = 'AED',
  AUD = 'AUD',
  BGN = 'BGN',
  BHD = 'BHD',
  CAD = 'CAD',
  CHF = 'CHF',
  CNH = 'CNH',
  CNY = 'CNY',
  CZK = 'CZK',
  DKK = 'DKK',
  EUR = 'EUR',
  GBP = 'GBP',
  HKD = 'HKD',
  HUF = 'HUF',
  ILS = 'ILS',
  JOD = 'JOD',
  JPY = 'JPY',
  KES = 'KES',
  KWD = 'KWD',
  MUR = 'MUR',
  MXN = 'MXN',
  NOK = 'NOK',
  NZD = 'NZD',
  OMR = 'OMR',
  PLN = 'PLN',
  QAR = 'QAR',
  RON = 'RON',
  SAR = 'SAR',
  SEK = 'SEK',
  SGD = 'SGD',
  THB = 'THB',
  TND = 'TND',
  TRY = 'TRY',
  USD = 'USD',
  ZAR = 'ZAR',
  ZMW = 'ZMW',
}
